# Generated by Django 5.0.8 on 2024-08-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.FileField(blank=True, null=True, upload_to='Portfolio Image', verbose_name='Photo')),
                ('cretae_date', models.DateTimeField(auto_now_add=True)),
                ('portfolio_name', models.TextField()),
                ('portfolio_image_detail', models.TextField()),
                ('portfolio_detail', models.TextField()),
                ('portfolio_about', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
