# Generated by Django 5.0.8 on 2024-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(blank=True, null=True, upload_to='product_image', verbose_name='Product Image')),
                ('product_status', models.TextField()),
                ('product_name', models.TextField()),
                ('product_location', models.TextField()),
                ('product_about', models.TextField()),
                ('product_price', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_image', verbose_name='Portfolio Image'),
        ),
    ]
