# Generated by Django 5.0.8 on 2024-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_bath_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_ft',
            field=models.IntegerField(default=0),
        ),
    ]
