# Generated by Django 5.0.8 on 2024-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_product_bath_count_product_product_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_bed_count',
            field=models.IntegerField(default=0),
        ),
    ]
