# Generated by Django 5.0.8 on 2024-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_product_bed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
