# Generated by Django 5.0.8 on 2024-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sale_type',
            field=models.TextField(default='as'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
