# Generated by Django 5.0.8 on 2024-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_product_sale_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_image', models.FileField(blank=True, null=True, upload_to='product_image', verbose_name='Product Image')),
                ('agent_details', models.TextField()),
                ('agent_about', models.TextField()),
                ('agent_img_detail', models.TextField()),
            ],
        ),
    ]
