# Generated by Django 5.0.8 on 2024-08-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_agent_agent_name_alter_agent_agent_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_name',
            new_name='agent_position',
        ),
    ]
