# Generated by Django 5.0.8 on 2024-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_service_alter_agent_agent_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_image', verbose_name='Portfolio Image'),
        ),
    ]
