# Generated by Django 5.0.8 on 2024-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_image', verbose_name='Portfolio Image'),
        ),
    ]
