# Generated by Django 5.0.8 on 2024-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_build_year',
            field=models.IntegerField(default=0),
        ),
    ]
