# Generated by Django 5.0.8 on 2024-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
