# Generated by Django 5.0.8 on 2024-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
