# Generated by Django 5.0.8 on 2024-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank=True, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_coupon', models.IntegerField(default=0)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_service', models.TextField(blank=True, null=True)),
                ('user_country', models.TextField(blank=True, null=True)),
                ('user_street', models.TextField(blank=True, null=True)),
                ('user_apartment', models.TextField(blank=True, null=True)),
                ('user_state', models.TextField(blank=True, null=True)),
                ('user_zip', models.TextField(blank=True, null=True)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('user_cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
