# Generated by Django 5.0.8 on 2024-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_coupon', models.IntegerField(default=0)),
                ('customer_phone', models.IntegerField(default=0)),
                ('customer_service', models.TextField(blank=True, null=True)),
                ('customer_country', models.TextField(blank=True, null=True)),
                ('customer_street', models.TextField(blank=True, null=True)),
                ('customer_apartment', models.TextField(blank=True, null=True)),
                ('customer_state', models.TextField(blank=True, null=True)),
                ('customer_zip', models.TextField(blank=True, null=True)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('customer_cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
